# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNativeWithExpo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  rn_path = "../node_modules/react-native"

  # Cocoapods ~> 1.5.0 does not support including local pods for which path
  # is a symlink. See PR https://github.com/CocoaPods/CocoaPods/pull/7781.

  # React dependencies
  pod 'React', path: rn_path, subspecs: [
    "Core",
    "ART",
    "RCTActionSheet",
    "RCTAnimation",
    "RCTCameraRoll",
    "RCTGeolocation",
    "RCTImage",
    "RCTNetwork",
    "RCTLinkingIOS",
    "RCTText",
    "RCTVibration",
    "RCTWebSocket",
    "DevSupport",
    "CxxBridge"
  ]
  pod 'yoga',
    :path => "#{rn_path}/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec",
    :inhibit_warnings => true

  # Expo modules
  pod 'EXCore', path: '../node_modules/expo-core/ios'
  pod 'EXReactNativeAdapter', path: '../node_modules/expo-react-native-adapter/ios'
  pod 'EXImageLoaderInterface', path: '../node_modules/expo-image-loader-interface/ios'
  pod 'EXFontInterface', path: '../node_modules/expo-font-interface/ios'

end
